Project Review PR
Mithi-code/react-air-quality pull request #3
Opened 2022-02-04 19:07 UTC by Mithi-code

### Countries Data Project

- Used git-flow
- Linter Checks
- React redux setup
- Reducers and actions for events 
- Using rest countries API to fetch country information
- Using weather API to fetch weather info of countries
- Search input where user can search their country name 
- Unit testing for reducers functions and snapshots of UI

2022-02-04 19:31 UTC, rukundoeric requested changes
Hi @Mithi-code, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-04 19:31 UTC, rukundoeric commented on README.md
> +
- [ ] <b>REQUIRED:</b> As it is required by the project, kindly deploy the app and share the link here. 
- [ ] <b>REQUIRED:</b> Also, you did not make a video presentation. Kindly make one with the following content(it must not be longer than 5min).
    -  Features of the project.
    - The video contains a clear and objective description about the project in professional English. The topic and purpose of the project are made clear.
    - The video contains a demo of the project, highlighting all the project features.
    - The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2022-02-04 19:31 UTC, rukundoeric commented on src/Components/Home.js
> +/* eslint-disable jsx-a11y/no-static-element-interactions */
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2022-02-04 19:31 UTC, rukundoeric commented on src/Components/Home.js
> +            // eslint-disable-next-line jsx-a11y/click-events-have-key-events
- [ ] <b>REQUIRED:</b> The same thing goes here.

2022-02-04 19:31 UTC, rukundoeric commented on src/Redux/Detail.js
> +// eslint-disable-next-line default-param-last
- [ ] <b>REQUIRED:</b> Here too.

2022-02-04 19:31 UTC, rukundoeric commented on src/Redux/HomeInfo.js
> +/* eslint-disable default-param-last */
- [ ] <b>REQUIRED:</b> Also here.

2022-02-04 19:31 UTC, rukundoeric commented on src/test/Details.test.js
> +// eslint-disable-next-line import/no-named-as-default
- [ ] <b>REQUIRED:</b>Here as well, you overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2022-02-04 19:31 UTC, rukundoeric commented on src/test/Details.test.js
> +});
- [ ] <b>REQUIRED:</b> As the project requires, kindly add more unit tests and integrated test for component. don't only test if snapshots are matching, but also test the actual content of the component.

2022-02-04 19:31 UTC, rukundoeric commented on src/test/Home.test.js
> +});
- [ ] <b>REQUIRED:</b>Here too, As the project requires, kindly add more unit tests and integrated tests for components. don't only test if snapshots are matching, but also test the actual content of the component.

2022-02-04 20:31 UTC, rukundoeric requested changes
Hi @Mithi-code, 

_Great job so far 👏 💯 👍. You've done well implementing some of the requested changes. However, there are still some which aren't addressed yet. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 
  - Addressed some of the issues raised from the previous review. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
  
  - N/A 

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-04 20:31 UTC, rukundoeric commented on src/Components/Home.js
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
- [ ] <b>REQUIRED:</b>As mentioned in the previous review, You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2022-02-04 20:31 UTC, rukundoeric commented on src/Redux/Detail.js
> +// eslint-disable-next-line default-param-last
- [ ] <b>REQUIRED:</b> Please! As I mentioned in the previous review, you are not allowed to ignore those rules. Kindly remove it and try to fix the issue.

2022-02-04 20:31 UTC, rukundoeric commented on src/Redux/HomeInfo.js
> +/* eslint-disable default-param-last */
- [ ] <b>REQUIRED:</b> Also here.

2022-02-04 20:31 UTC, rukundoeric commented on src/test/Details.test.js
> +// eslint-disable-next-line import/no-named-as-default
- [ ] <b>REQUIRED:</b> And here too.

2022-02-04 20:31 UTC, rukundoeric commented on src/test/Details.test.js
> +});
- [ ] <b>REQUIRED:</b> As I mentioned in the previous review, the project requires to make sure that the project has unit and integrated tests. which means, not only checking if the component renders but also checking what it renders with(the actual content). 

![scrnli_2_4_2022_10-22-05 PM](https://user-images.githubusercontent.com/45217364/152598835-4e5c294c-39a2-4dc0-b708-ed7e014dd526.png)

2022-02-04 20:31 UTC, rukundoeric commented on src/test/Home.test.js
> +});
- [ ] <b>REQUIRED:</b>The same thing here.

2022-02-05 21:09 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Mithi-code, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/749155b89333c6d89386f5c98dd110e234a00f2aa1e864a5b3fecaf089aedb27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36664a31424d375232454252446e784b2f67697068792e676966)

Cheers and Happy coding!👏👏👏

2022-02-05 21:09 UTC, merged